# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'csv'

gem "colorize", "~> 0.8.1"

gem "TableCSV", "~> 0.1.0"

gem "cli-colorize", "~> 2.0"
